name: minenger
description: Minenger App

publish_to: 'pub.dev' # Remove this line if you wish to publish to pub.dev

version: 1.0.27

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  webview_flutter: ^3.0.4
  animated_splash_screen: ^1.3.0
  flutter_animated_dialog: ^2.0.1
  animated_button: ^0.2.0
  carousel_slider: ^4.1.1
  intl_phone_field: ^3.1.0
  google_mobile_ads: ^2.4.0
  shared_preferences: ^2.1.0
  dio: 5.1.1
  get_it: ^7.2.0
  intl: ^0.17.0
  flutter_local_notifications: ^9.7.0
  http: ^0.13.6
  html: ^0.15.3
  animated_text_kit: ^4.2.2
  material_dialogs: ^1.1.4
  flip_card: ^0.7.0
  clipboard: ^0.1.3
  easy_animate: ^0.0.3
  flutter_gif: ^0.0.4
  awesome_notifications: ^0.7.4+1
  email_validator: ^2.1.16
  hive_flutter: ^1.1.0
  flutter_animation_progress_bar: ^2.3.1
  icons_plus: ^4.0.0
  json_serializable: ^3.5.1
  sms_otp_auto_verify: ^2.1.0
  exprollable_page_view: ^1.0.0-rc.2



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_lints: ^2.0.0
flutter_launcher_icons:
  path: ../

flutter_icons:
  image_path_android: "assets/msplash.png"
  image_path_ios: "assets/msplash.png"
  android : true
  ios: true
  web: false
  windows: false
  #adaptive_icon_backgrund: "assets/icon.png"
  #adaptive_icon_foreground: "assets/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/gif/

  fonts:
    - family: Akrobat-Regular
      fonts:
        - asset: fonts/akrobat-regular.otf

    - family: Akrobat-Semibold
      fonts:
        - asset: fonts/akrobat-semibold.otf

    - family: Oswald-Regular
      fonts:
        - asset: fonts/oswald-regular.ttf

