name: minenger
description: Minenger App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  webview_flutter: ^3.0.4
  animated_splash_screen: ^1.3.0
  flutter_animated_dialog: ^2.0.1
  animated_button: ^0.2.0
  carousel_slider: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_lints: ^2.0.0
flutter_launcher_icons:
  path: ../

flutter_icons:
  #image_path_android: "assets/icon.png"
  #image_path_ios: "assets/icon.png"
  android : true
  ios: true
  web: false
  windows: false
  #adaptive_icon_backgrund: "assets/icon.png"
  #adaptive_icon_foreground: "assets/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Akrobat-Regular
      fonts:
        - asset: fonts/akrobat-regular.otf

    - family: Akrobat-Semibold
      fonts:
        - asset: fonts/akrobat-semibold.otf


    - family: Oswald-Regular
      fonts:
        - asset: fonts/oswald-regular.ttf

